Add back in deploy step

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -74,8 +74,6 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
 
-    # Set $PROD_COLOR env var through the complicated method github actions requires
-    # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
     - name: Identify production cluster, either blue or green
       id: prod-cluster-color
       env:
@@ -89,16 +87,15 @@ jobs:
           #dig ${{ secrets.PROD_ENDPOINT }} +short | grep -o "blue\|green"
           aws route53 list-resource-record-sets --hosted-zone-id ${{ secrets.PHILACITY_ZONE_ID }} --query "ResourceRecordSets[?Name == '${{ secrets.PROD_ENDPOINT }}.']" | grep -o "blue\|green"
           echo "PROD_COLOR=$(aws route53 list-resource-record-sets --hosted-zone-id ${{ secrets.PHILACITY_ZONE_ID }} --query "ResourceRecordSets[?Name == '${{ secrets.PROD_ENDPOINT }}.']" | grep -o "blue\|green")" >> $GITHUB_ENV
-
-
-    - name: Set engine hostname to the staging database for testing against.
+           
+    - name: Set engine hostname based on prod color
       env:
         PROD_ENDPOINT: ${{ secrets.PROD_ENDPOINT }}
       run: |
         if [[ "$PROD_COLOR" -eq "blue" ]]; then
-           echo "ENGINE_HOST=${{ secrets.GREEN_ENGINE_CNAME }}" >> $GITHUB_ENV
-        elif [[ "$PROD_COLOR" -eq "green" ]]; then
            echo "ENGINE_HOST=${{ secrets.BLUE_ENGINE_CNAME }}" >> $GITHUB_ENV
+        elif [[ "$PROD_COLOR" -eq "green" ]]; then
+           echo "ENGINE_HOST=${{ secrets.GREEN_ENGINE_CNAME }}" >> $GITHUB_ENV
         fi
 
     - name: Pull private passyunk data
@@ -156,3 +153,75 @@ jobs:
         custom-facts: |
           - name: Job Progress
             value: Build successful for commit ID ${{ env.GITHUB_SHA_SHORT }}, pushing new AIS docker image to ECR
+
+  deploy:
+
+    name: Deploy to production ECS cluster
+    # needs prior job of 'build' to not fail.
+    #needs: [build, pre-build]
+    needs: build
+    #runs-on: ubuntu-latest
+    runs-on: ais-runner
+         
+
+    steps:
+
+    # https://github.com/aws-actions/amazon-ecr-login
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-east-1
+
+    # Set $PROD_COLOR env var through the complicated method github actions requires
+    # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-environment-variable
+    - name: Identify production cluster, either blue or green
+      id: prod-cluster-color
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        PROD_ENDPOINT: ${{ secrets.PROD_ENDPOINT }}
+      run: |
+          # Note: a simple dig doesn't work from in office.
+          # Run the command manually first so we're sure it works, otherwise the var assignment hides errors.
+          #echo "PROD_COLOR=$(dig ${{ secrets.PROD_ENDPOINT }} +short | grep -o "blue\|green")" >> $GITHUB_ENV
+          #dig ${{ secrets.PROD_ENDPOINT }} +short | grep -o "blue\|green"
+          aws route53 list-resource-record-sets --hosted-zone-id ${{ secrets.PHILACITY_ZONE_ID }} --query "ResourceRecordSets[?Name == '${{ secrets.PROD_ENDPOINT }}.']" | grep -o "blue\|green"
+          echo "PROD_COLOR=$(aws route53 list-resource-record-sets --hosted-zone-id ${{ secrets.PHILACITY_ZONE_ID }} --query "ResourceRecordSets[?Name == '${{ secrets.PROD_ENDPOINT }}.']" | grep -o "blue\|green")" >> $GITHUB_ENV
+      
+    - name: Force deploy to ECS cluster
+      run: |
+          echo "Deploying to $PROD_COLOR"
+          aws ecs update-service --cluster ais-$PROD_COLOR-cluster \
+          --service ais-$PROD_COLOR-api-service --force-new-deployment --region us-east-1
+          aws ecs wait services-stable --cluster ais-$PROD_COLOR-cluster \
+          --service ais-$PROD_COLOR-api-service --region us-east-1
+    - name: Confirm LB target group health
+      run: |
+        blue_tg_arn=$(aws elbv2 describe-target-groups | grep "blue-tg" | grep TargetGroupArn| cut -d"\"" -f4)
+        green_tg_arn=$(aws elbv2 describe-target-groups | grep "green-tg" | grep TargetGroupArn| cut -d"\"" -f4)
+        if [[ "$PROD_COLOR" -eq "blue" ]]; then
+              echo "blue"
+              aws elbv2 describe-target-health --target-group-arn $blue_tg_arn | grep "\"healthy\""
+              echo $?
+        elif [[ "$PROD_COLOR" -eq "green" ]]; then
+              echo "green"
+              aws elbv2 describe-target-health --target-group-arn $green_tg_arn | grep "\"healthy\""
+              echo $?
+        fi
+
+  # https://github.com/marketplace/actions/microsoft-teams-deploy-card
+  # Using replacement fork for toko-bifrost, context for why: https://github.com/toko-bifrost/ms-teams-deploy-card/issues/33#issuecomment-888466503 
+    #- uses: toko-bifrost/ms-teams-deploy-card@master
+    - uses: patrickpaulin/ms-teams-deploy-card@master
+      if: always()
+      with:
+        GITHUB-TOKEN: ${{ github.token }}
+        WEBHOOK-URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
+        card-layout-exit: complete
+        show-on-start: false
+        show-on-exit: true
+        custom-facts: |
+          - name: Job Progress
+            value: Deployed to ${{ env.PROD_COLOR }} ECS cluster.
